[build-system]
requires = ["setuptools>=68.0.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 150

[tool.flake8]
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "paper"
]
