name: run_tests

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run_tests:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9 environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Black formatting
        run: |
          black --check .

      - name: Flake8 linting
        run: |
          flake8 .

      - name: Mypy test
        run: |
          mypy --config-file mypy.ini .

      - name: Run unit tests
        run: |
          python -m pytest -vv
